export const Estudios = [
    "Primario",
    "Secundario",
    "Terciario",
    "Universitario",
    "Otro"]
    
export const Generos = [
    "Femenino",
    "Masculino",
    "No-binario",
    "Otro"]

export const Tareas = [
    {disabled:"disabled", text: "Especificar tarea"},
    {disabled:"", text: "Albañil"},
    {disabled:"", text: "Alimetos"},
    {disabled:"", text: "Cartonero"},
    {disabled:"", text: "Construcción"},
    {disabled:"", text: "Construcción, Comercialización"},
    {disabled:"", text: "Comercialización"},
    {disabled:"", text: "Cuidados"},
    {disabled:"", text: "Proyectos Socio-Productivos"},
    {disabled:"", text: "Reciclado"},
    {disabled:"", text: "Rural"},
    {disabled:"", text: "Tareas de Cuidados y servicios Socio Comunitarios"},
    {disabled:"", text: "Textil"},
    {disabled:"", text: "Otro"}]

export const Barrios = [
    {disabled:"disabled", text: "Especificar barrio"},
    {disabled:"", text: "barrio-1"},
    {disabled:"", text: "barrio-2"},
    {disabled:"", text: "barrio-3"},
    {disabled:"", text: "barrio-4"},
    {disabled:"", text: "Otro"}]

export const Organizaciones = [
    {disabled:"disabled", text: "Todas las organizaciones"},
    {value:"acplaiba", text: "ACPLAIBA"},
    {value:"abrazoPeronista", text: "Agrupacion Abrazo Peronista"},
    {value:"laEva", text: "Agrupacion La Eva"},
    {value:"laPeronista", text: "Agrupacion La Peronista"},
    {value:"peronista17octubre", text: "Agrupacion Peronista 17 octubre"},
    {value:"villaElvira", text: "Agrupacion Villa Elvira"},
    {value:"calle13", text: "Calle 13"},
    {value:"canpo", text: "CANPO"},
    {value:"casaParaLaVictoria", text: "Casa para la Victoria"},
    {value:"companerosEnLucha", text: "Compañeros en Lucha"},
    {value:"corrienteNuestraPatria", text: "Corriente Nuestra Patria"},
    {value:"corrientePeronistaParaLaVictoria", text: "Corriente Peronista para a Victoria"},
    {value:"corrientePoliticaySocialLaGerman", text: "Corriente Politica y Social La German"},
    {value:"ctaAutonoma", text: "CTA Autonoma"},
    {value:"espacioSocialYcooperativo", text: "Espacio social y cooperativo"},
    {value:"febo", text: "FEBO"},
    {value:"frenteSocialNuevaIndependencia", text: "Frente Social Nueva "},
    {value:"ellasHacen", text: "Frente Territorial Ellas Hacen"},
    {value:"fuegasHerramientasFeministas", text: "Fuegas Herramientas Feministas"},
    {value:"gritoDeCorazon", text: "Grito de Corazon"},
    {value:"juntosSomosMas", text: "Juntos Somos Mas (ADSL)"},
    {value:"juventudRenovadora", text: "Juventud Renovadora"},
    {value:"laAgustinTosco", text: "La Agustin Tosco"},
    {value:"laBajada", text: "La Bajada"},
    {value:"laCooke", text: "La Cooke"},
    {value:"laMilitante", text: "La Militante"},
    {value:"las3Banderas", text: "Las 3 Banderas"},
    {value:"movimientoPatriaGrande", text: "Movimiento Patria Grande"},
    {value:"mujeresDelOeste", text: "Mujeres del Oeste"},
    {value:"mujeresPlatensesUnidas", text: "Mujeres Platenses Unidas"},
    {value:"orgullosamentePlatense", text: "Orgullosamente Platense"},
    {value:"pKPulki", text: "PK / Pulki"},
    {value:"pochoVive", text: "Pocho Vive"},
    {value:"puraLealtad", text: "Pura Lealtad"},
    {value:"resistiendoConAguante", text: "Resistiendo con Aguante"},
    {value:"terceraPosicion", text: "Tercera Posicion"},
    {value:"unidadBasica", text: "Unidad Basica 27 de Octubre - Nestor Vive"},
    {value:"unidosyEmpoderados", text: "Unidos y Empoderados"},
    {value:"unionPeronistaPlatense", text: "Unión Peronista Platense"},
    {value:"variasIniciativasTerritoriales", text: "Varias iniciativas territoriales"},
    {value:"agrupacionBarrioHipodromo", text: "Agrupacion Barrio Hipodromo"},
    {value:"25deMayo", text: "25 de Mayo"},
    {value:"laEscuelitaLasvikingas", text: "La Escuelita - Las vikingas"}
]
export const Referentes = [
    {disabled:"disabled", text: "Todos los referentes"},
    {value:"Carlos Pose", text: "Carlos Pose", orga:"acplaiba"},
    {value:"Jesus Helguera", text: "Jesus Helguera", orga:"AgrupacionAbrazoPeronista"},
    {value:"ref", text: "ref", orga:"agrupacionAbrazoPeronista"},
    {value:"Rafael Irigoiti", text: "Rafael Irigoiti", orga:"agrupacionLaEva"},
    {value:"Virginia Rodriguez", text: "Virginia Rodriguez", orga:"agrupacionLaPeronista"},
    {value:"Gustavo Belingeri", text: "Gustavo Belingeri", orga:"peronista17octubre"},
    {value:"Negro Fernandez", text: "Negro Fernandez", orga:"peronista17octubre"},
    {value:"Carlos Rioja", text: "Carlos Rioja", orga:"villaElvira"},
    {value:"Gustavo Oliva", text: "Gustavo Oliva", orga:"calle13"},
    {value:"Sergio Dumrauf", text: "Sergio Dumrauf", orga:"canpo"},
    {value:"Carola Corra", text: "Carola Corra", orga:"casaParaLaVictoria"},
    {value:"Natalia Mainoldi", text: "Natalia Mainoldi", orga:"casaParaLaVictoria"},
    {value:"Neko Ibarra", text: "Neko Ibarra", orga:"companerosEnLucha"},
    {value:"Cintia Mansilla", text: "Cintia Mansilla", orga:"corrienteNuestraPatria"},
    {value:"Nicolas Carvalho", text: "Nicolas Carvalho", orga:"corrientePeronistaParaLaVictoria"},
    {value:"Cesar Larez", text: "Cesar Larez", orga:"corrientePoliticaySocialLaGerman"},
    {value:"Kivi Torres", text: "Kivi Torres", orga:"ctaAutonoma"},
    {value:"Lorena Palchasti", text: "Lorena Palchasti", orga:"espacioSocialYcooperativo"},
    {value:"Juana Camilletti", text: "Juana Camilletti", orga:"febo"},
    {value:"Rolando Salas", text: "Rolando Salas", orga:"frenteSocialNuevaIndependencia"},
    {value:"Maria Julieta Rosas", text: "María Julieta Rosas", orga:"ellasHacen"},
    {value:"Juliana Brizuela", text: "Juliana Brizuela", orga:"fuegasHerramientasFeministas"},
    {value:"Nicolas Pereyra", text: "Nicolas Pereyra", orga:"gritoDeCorazon"},
    {value:"Ale Gutierrez", text: "Ale Gutierrez", orga:"juntosSomosMas"},
    {value:"Melli Diaz", text: "Melli Diaz", orga:"juventudRenovadora"},
    {value:"Diego Suarez", text: "Diego Suarez", orga:"laAgustinTosco"},
    {value:"Luis Pollero", text: "Luis Pollero", orga:"laBajada"},
    {value:"Lalo Marchesi", text: "Lalo Marchesi", orga:"laCooke"},
    {value:"Alberto Chiffel", text: "Alberto Chiffel", orga:"laMilitante"},
    {value:"Chino Giles", text: "Chino Giles", orga:"las3Banderas"},
    {value:"Pablo Allo", text: "Pablo Allo", orga:"movimientoPatriaGrande"},
    {value:"Valeria Lopez", text: "Valeria Lopez", orga:"mujeresDelOeste"},
    {value:"Flor Espinosa", text: "Flor Espinosa", orga:"mujeresPlatensesUnidas"},
    {value:"Diego Gallardo", text: "Diego Gallardo", orga:"orgullosamentePlatense"},
    {value:"Luis Sannen", text: "Luis Sannen", orga:"pKPulki"},
    {value:"Leo Lattini", text: "Leo Lattini", orga:"pochoVive"},
    {value:"Fernando Ramos", text: "Fernando Ramos", orga:"puraLealtad"},
    {value:"Pitu Morales", text: "Pitu Morales", orga:"resistiendoConAguante"},
    {value:"Juan Granillo", text: "Juan Granillo", orga:"terceraPosicion"},
    {value:"Miguel Barsabal", text: "Miguel Barsabal", orga:"unidadBasica"},
    {value:"Poly Tritten", text: "Poly Tritten", orga:"unidosyEmpoderados"},
    {value:"Carolina Gonzalez", text: "Carolina Gonzalez", orga:"unionPeronistaPlatense"},
    {value:"Mario Lopez", text: "Mario Lopez", orga:"variasIniciativasTerritoriales"},
    {value:"Javier Garcia", text: "Javier Garcia", orga:"variasIniciativasTerritoriales"},
    {value:"Marcelo Jalil", text: "Marcelo Jalil", orga:"agrupacionBarrioHipodromo"},
    {value:"Carlos Di Francisco", text: "Carlos Di Francisco", orga:"25deMayo"},
    {value:"Ruben Delia", text: "Ruben Delia", orga:"25deMayo"},
    {value:"Mariela Orieta", text: "Mariela Orieta", orga:"laEscuelitaLasvikingas"},    
]
